name: Setup Repo
description: Setups up correct node version and installs dependencies

inputs:
  framework-path:
    required: true
    type: string

runs:
  using: composite

  steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Setup node
    uses: actions/setup-node@v3
    with:
      node-version-file: 'inputs.framework/.nvmrc'    